/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthHeader: typeof import('./src/components/auth/AuthHeader.vue')['default']
    FullScreenWrapper: typeof import('./src/components/shared/FullScreenWrapper.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainFooter: typeof import('./src/components/home/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/home/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
