apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-backend
  template:
    metadata:
      labels:
        app: rails-backend
    spec:
      containers:
        - name: rails-backend
          image: f136pix/messaging-server
          env:
            - name: DATABASE_USERNAME
              value: admin
            - name: DATABASE_PASSWORD
              value: paS5w0rD!
            - name: DATABASE_HOST
              value: pgsql-clusterip-srv
            - name: DATABASE_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: rails-backend
  ports:
    - name: rails-backend
      protocol: TCP
      targetPort: 3000
      port: 3000

